### ISSUE TITLE
クラスファイルやIDEの構成ファイルをgit管理対象外してください

### ISSUE THREAD

**Issue by kazuki43zoo** [j-tejima/Tutorial#1]
一般的に、以下のディレクトリ・ファイルはgitで管理しません。

* target : mavenのビルド結果を格納するディレクトリ
* .settings : Eclipseの構成設定ファイルを格納するディレクトリ
* .classpath : Eclipseのクラスパス設定ファイル
* .project : Eclipseのプロジェクト設定ファイル

基本的には・・・srcとpom.xmlのみ管理します。（プロジェクトによって＋αはありえますが、基本は←です）

何もしないとgit管理対象になってしまうので、管理対象外のディレクトリやファイルについては、git addする前に・・・.gitignoreというファイル作成して指定しておく必要があります。

http://qiita.com/anqooqie/items/110957797b3d5280c44f

既に管理対象にしてしまったファイルを後から管理対象から除外することもできたと思いますが・・・
もしやり方がわからなければ、１からやりなおしてpushでもとりあえずＯＫです。

**Comment by j-tejima** [comment]
.gitignoreファイルを作成して以下を管理対象から外しました。
・target
・.settings
・.classpath
・.project

**Comment by btshimizukza** [comment]
:+1:

**Comment by kazuki43zoo** [comment]
:+1:

**Comment by kazuki43zoo** [comment]
fixed via deb08ea799884e45b6713ccc568a90727e497e0b
